### ISSUE TITLE
Adjust font colors acc. to Background

### ISSUE THREAD

**Issue by manishkrjha** [manishkrjha/PAWsite#1]
Font colours are poorly implemented at a couple of places due to which text is not visible. Change that to #000000.

![Screenshot (291)](https://user-images.githubusercontent.com/51622948/95062986-5d8d8800-071b-11eb-98d4-58bedb3a1be1.png)

**Comment by drishyadamodaran** [comment]
can i?

**Comment by manishkrjha** [comment]
> can I?

Sure, just make sure you aren't committing your changes on the master branch.

**Comment by drishyadamodaran** [comment]
ok @manishkrjha

**Comment by drishyadamodaran** [comment]
@manishkrjha done!!

**Comment by waridrox** [comment]
@manishkrjha Is it still open for contribution ?

**Comment by manishkrjha** [comment]
> @manishkrjha Is it still open for contribution ?

Sorry It's already done
